export const ASK_WHAT_TO_WORK_ON_DESCRIPTION = [
  'Ask what to work on next. Call this at the start of a session, before planning or building.',
  'It returns the next queued work to implement (if any) and a sessionId.',
  'It also lists draft work that still needs a relentless interview.',
  'Implement queued work first. When finished, call tell_what_was_built with the same sessionId.',
  'For a draft, call ask_interview_questions until there are no more questions.',
  'Paused queued items are held and will not be returned.',
].join('\n');

export const ASK_INTERVIEW_DESCRIPTION = [
  'Run a relentless interview on a draft. Ask 2–4 multiple-choice questions about the plan.',
  'The dashboard shows them under the draft card. This call waits until they are answered.',
  'Each answer is stored as a decision bullet on the work item.',
  'Keep calling with follow-up questions until the plan is sharp. Then pass questions: [] to queue it.',
].join('\n');

export const TELL_WHAT_WAS_BUILT_DESCRIPTION = [
  'Tell the work plugin what you just built. Call this after the work is done, at the end of the session.',
  'Always pass the sessionId from ask_what_to_work_on, plus title and description (what changed and why).',
  'Pass every applicable artifact kind. Omit kinds that do not apply. At least one artifact kind is required.',
  '',
  'Highlight the change. Artifacts should show what is different versus before, not only the new end state.',
  'Prefer visual, /show-me-style views: component trees, file trees, call trees, diffs, and Mermaid of the change.',
  'UI HTML is a visual preview in the same style and design system as the app being built.',
  'Preview a changed screen, or a changed component when the scope was smaller. Use realistic mock data.',
  'Mark the changed region in the HTML (callout, badge, before/after). Inline icons and images as files in assets.',
  'The review questionnaire is the questions param (shown under the preview). The HTML is the product UI.',
  '',
  'Details',
  'ui: one self-contained HTML document per changed screen or component. Match type, color, spacing, and components.',
  'Fill it with realistic mock data for this product’s scenarios and use cases (real names, amounts, statuses, dates).',
  'Not lorem ipsum or placeholders. Inline CSS and JS. No bundler. Include icons/images via assets (see below).',
  'Include the app’s own controls (radios, forms, notes, submit, iframes) when those are part of the product.',
  'The HTML does not need a review questionnaire — that is the separate questions param, rendered below the preview.',
  'Each ui.pages entry is one surface. Split unrelated screens or components into several entries.',
  'questions: structured payload the dashboard shows under the matching preview. questions.ui filename matches a ui.pages file.',
  'Each question.context is the brief a follow-up agent gets when that question is answered (queued work).',
  'api: every HTTP route added, modified, or removed — real paths from this app, with method, path, and what changed.',
  'algorithm: name, what changed vs before, and post-change pseudocode using this product’s real steps and domain terms.',
  'dataModel: Mermaid erDiagram or classDiagram of the model after the change, with real entities, fields, and relations.',
  'moduleStructure: Mermaid of the modules after the change, with real module names. Module questions go in questions.modules.',
  'outline: compact /show-me change outline — trees, diffs, call flow — focused on what changed.',
  'backend: plain English for other backend work not covered by the other kinds.',
  'assets: icons and images used in the HTML. filename + mimeType + base64. Reference them by filename in src or CSS url().',
  'They are inlined as data URIs so each HTML file stays self-contained. You may also POST them to HTTP /api/assets with sessionId.',
].join('\n');
