export { createUi } from './core/create-ui.js';
export { applyUiPlugins } from './core/apply.js';
export { layoutPlugin } from './core/layout-plugin.js';
export { DEFAULT_PANELS, DEFAULT_LAYOUT, DASHBOARD_LAYOUTS, ALL_PANELS } from './core/slots.js';
export type { DashboardLayoutId, DashboardPanelId } from './core/slots.js';
export type { UiPlugin, UiSurface, UiProviderContribution, UiHooks, SurfaceProps, UiPluginKind } from './core/plugin.js';
export type { UiHost, CreateUiOptions } from './core/create-ui.js';
export { DashboardShell } from './dashboard/shell.js';
export { workUiPlugin, createHttpWorkClient } from './plugins/index.js';
export type { HttpWorkClientOptions, WorkClient, WorkItem, WorkArtifact } from './plugins/index.js';
export * from './design/index.js';
